# Generated by Django 4.2.17 on 2025-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
