# Generated by Django 4.2.17 on 2025-01-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_form_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choices',
            new_name='choice',
        ),
    ]
