# Generated by Django 4.2.17 on 2025-01-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_choices_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choices',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice',
            new_name='choices',
        ),
    ]
