# Generated by Django 4.2.17 on 2025-01-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_responseanswer_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Responses',
        ),
    ]
