# Generated by Django 4.2.17 on 2025-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_response_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='responses',
            field=models.ManyToManyField(blank=True, to='App.responseanswer'),
        ),
    ]
